### PR TITLE
chore: change fallback language for ukr

### PR DESCRIPTION
**Pull request by lazysoundsystem**
[DSR-388] [DSR-374]

@teodorescuserban Please note that this isn't tested, but looks like it should work based on the ticket description.

[DSR-388]: https://humanitarian.atlassian.net/browse/DSR-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DSR-374]: https://humanitarian.atlassian.net/browse/DSR-374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by teodorescuserban — APPROVED** [review]

**Comment by lazysoundsystem** [comment]
@teodorescuserban - I tried to see what's going on with the cache but no further forward, yet.

I did find the uk.js locale file, and I've tried reverting the fallback (though I don't know if it could have caused the issue) and replaced the months with their Ukranian names.

Again, needs proper testing on staging!

**Comment by lazysoundsystem** [comment]
I tried re-deploying the dev branch, and I get the same issue there, on a hunch, I tried switching the fallback language to French, but that doesn't solve anything.

Changing the language for the months seems easy. Still trying to work out why Ukrainian pages won't open in a new tab, or from a link (as opposed to opening it by left-clicking the link in the homepage so it opens in the same tab).

**Comment by lazysoundsystem** [comment]
Reverted back to the 'en' fallback. I'll deploy again to the dev site and maybe the cache will clear itself over the weekend. Or maybe we can try deploying to the preview or training sites to check if it's this change that causes the problem.

**Comment by lazysoundsystem** [comment]
The Ukrainian sitreps were republished on the dev site, while the fallback was already in place, and they're opening correctly in new tabs now.

I've also tried this on the Training environment: https://training.demo.reports-unocha-org.ahconu.org/ and it's working as expected.

I think it's ready to merge - re-requesting review from Serban for confirmation.

**Comment by lazysoundsystem** [comment]
Ready to merge and deploy. https://humanitarian.atlassian.net/browse/DSR-388?focusedCommentId=138157

**Review by teodorescuserban — COMMENTED** [review]
👍

**Pull request merged**
