### PR TITLE
DSR-381: upgrade to node.js 16

### PR DESCRIPTION
**Pull request by rupl**
# DSR-381

Please follow the docs in https://github.com/UN-OCHA/reports-site-stack/pull/306 to review this PR. Once we deem it satisfactory, this PR can be merged.

### CODE REVIEW

**Comment by rupl** [comment]
Ping to @teodorescuserban to confirm that these build errors can be ignored.

I think it's a chicken-and-egg problem: until we merge the PR, the `dev` ECR image contains node.js 12 and it will complain about versions.

**Comment by rupl** [comment]
I noticed that the site wouldn't build and I have to imagine it's because the dependencies are about a year out of date. Since we did the upgrade work in #406 I have merged that branch into this one to unify all the upgrades in one go.

**Review by lazysoundsystem — APPROVED** [review]
Looking right, I think bumping the node version in .travis.yml should fix the tests: https://github.com/UN-OCHA/reports-site/blob/344a2d6328962c6d928fda6c4a0edc5bb5b842fc/.travis.yml#L3

**Comment by rupl** [comment]
lol, the last commit on the Travis file was me forgetting to upgrade node.js when we moved to 12 😆

**Pull request merged**
